import { v4 as uuid } from "uuid"
import { db } from "./db";
import { getValidateTokenbyEmail } from "@/data/validateToken";
import { getPasswordResetTokenbyEmail } from "@/data/password-reet-token";


export const generatePasswordResetToken= async(email:string)=>{


    const token = uuid();
    const expires = new Date (new Date().getTime() + 3600 *1000);  
    const existingToken =  await  getPasswordResetTokenbyEmail(email);


    if(existingToken){
        await db.passwordResetToken.delete({
            where:{id:existingToken.id},
            
        })
    }
   

    const passwordResetToken = await db.passwordResetToken.create({
        data:{
            token,
            expires,
            email
        }
    }) 
  
    return passwordResetToken;

}






// verification token generated by email and by token








export const generateVerificationToken= async(email:string)=>{


    const token = uuid();
    const expires = new Date (new Date().getTime() + 3600 *1000);
   
  
    
    const existingToken =  await getValidateTokenbyEmail(email);


    if(existingToken){
        await db.verificationToken.delete({
            where:{id:existingToken.id},
            
        })
    }
   

    const verificationToken = await db.verificationToken.create({
        data:{
            token,
            expires,
            email
        }
    }) 
  
    return verificationToken;

}